on: [push, workflow_dispatch]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Testing Action
    steps:
      - name: Run
        uses: komish/reusable-actions-hackery@main
        with:
          image: quay.io/opdev/simple-demo-operator:latest

  example_job_container:
    runs-on: ubuntu-latest
    name: Testing Action
    steps:
      - name: Run
        uses: docker://quay.io/opdev/preflight:stable