on: [push, workflow_dispatch]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Testing Action
    steps:
      - name: Run
        uses: komish/reusable-actions-hackery@main
        with:
          image: quay.io/opdev/simple-demo-operator:latest

  example_job_container:
    runs-on: ubuntu-latest
    name: Testing Action
    container: quay.io/opdev/preflight:stable
    steps:
      - name: Show Version
        run: |
          preflight --version
      - name: Check Container
        env:
          PFLT_PYXIS_API_TOKEN: ${{ secrets.PFLT_PYXIS_API_TOKEN }}
          PFLT_CERTIFICATION_COMPONENT_ID: 123456789000
        run: |
          preflight check container quay.io/opdev/simple-demo-operator:latest
          ls -lah