on: [push, workflow_dispatch]

jobs:
  example_job_container:
    runs-on: ubuntu-latest
    name: Testing Action
    container: quay.io/opdev/preflight:stable
    steps:
      - name: Show Version
        run: |
          preflight --version
      - name: Check Container
        run: |
          preflight check container \
            quay.io/opdev/simple-demo-operator:latest
          ls -lah
      - name: upload log
        uses: actions/upload-artifact@v4
        with:
          name: preflight-results
          path: |
            preflight.log
            artifacts
          if-no-files-found: error
          retention-days: 1
        